import Img1 from './images/slider/1.png';
import Img2 from './images/slider/2.png';
import Img3 from './images/slider/3.png';
import BurgerImg from './images/burger.svg';
import PizzaImg from './images/pizza.svg';
import SaladImg from './images/salad.svg';
export default [
  {
    _id: '1',
    title: 'Chicken Burger burger burger',
    slug: 'chicken-burger',
    type: 'burger',
    icon: BurgerImg,
    images: Img1,
    thumb: [Img1, Img2, Img3],
    alt: 'Veggi Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',

    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 21,
    count: 1,
  },
  {
    _id: '2',
    title: 'Cheese Burger',
    slug: 'cheese-burger',
    type: 'burger',
    icon: BurgerImg,
    images: Img2,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 19,
    count: 1,
  },
  {
    _id: '3',
    title: 'Pepperoni',
    slug: 'pepperoni-pizza',
    type: 'pizza',
    icon: PizzaImg,
    images: Img3,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 50,
    count: 1,
  },
  {
    _id: '4',
    title: 'Vegetarian',
    slug: 'vegetarian-pizza',
    type: 'pizza',
    icon: PizzaImg,
    images: Img1,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 15,
    count: 1,
  },
  {
    _id: '5',
    title: 'Chicken Salad',
    slug: 'chicken-salad',
    type: 'salad',
    icon: SaladImg,
    images: Img2,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 10,
    count: 1,
  },
  {
    _id: '6',
    title: 'Greek Salad',
    slug: 'greek-salad',
    type: 'salad',
    icon: SaladImg,
    images: Img3,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 17,
    count: 1,
  },
  {
    _id: '7',
    title: 'Greek Salad',
    slug: 'greek-salad',
    type: 'salad',
    icon: SaladImg,
    images: Img3,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 17,
    count: 1,
  },
  {
    _id: '8',
    title: 'Greek Salad',
    slug: 'greek-salad',
    type: 'salad',
    icon: SaladImg,
    images: Img3,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 17,
    count: 1,
  },
  {
    _id: '9',
    title: 'Greek Salad',
    slug: 'greek-salad',
    type: 'salad',
    icon: SaladImg,
    images: Img3,
    thumb: [Img1, Img2, Img3],
    alt: 'Pepperoni Pizza',
    ingredients: 'Dough, Mozzarella, Tomatoes, Basil, Sauce, Parmesan',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque molestias quas eveniet delectus, voluptatibus corrupti illum laboriosam iusto vero quod.',
    price: 17,
    count: 1,
  },
];
